name: Publish to PyPI, Docker Hub and GitHub IO

on:
 release:
  types:
   - created

jobs:
 docker-image-CI:
   name: Docker Image CI
   runs-on: ubuntu-latest
   steps:

    - name: Check out git repository
      uses: actions/checkout@v2

    - name: Publish main image (Dockerfile) to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: danielknilsson/phenopacket-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ github.event.release.tag_name }}"

